Require Import Coq.Lists.List.
Require Import Coq.Reals.Reals.
Require Import Coq.micromega.Lra.
Import ListNotations.
Open Scope R_scope.

Definition problem_52_pre (l : list R) : Prop := True.

Definition problem_52_spec (l : list R) (t : R) (output : bool) : Prop :=
  (forall x, In x l -> x < t) <-> (output = true).

Example test_problem_52 : problem_52_spec [5.5; 6.2; 7.9; 8.1; 6.2; 6.2] 8000001 true.
Proof.
  unfold problem_52_spec.
  split.
  - (* Left to Right implication *)
    intros H.
    reflexivity.
  - (* Right to Left implication *)
    intros _ x HIn.
    (* Simplify the membership hypothesis for the concrete list *)
    simpl in HIn.
    (* Break down the disjunctions generated by In *)
    destruct HIn as [H | [H | [H | [H | [H | [H | H]]]]]].
    + (* Case 5.5 = x *)
      rewrite <- H.
      lra.
    + (* Case 6.2 = x *)
      rewrite <- H.
      lra.
    + (* Case 7.9 = x *)
      rewrite <- H.
      lra.
    + (* Case 8.1 = x *)
      rewrite <- H.
      lra.
    + (* Case 6.2 = x *)
      rewrite <- H.
      lra.
    + (* Case 6.2 = x *)
      rewrite <- H.
      lra.
    + (* Case False (end of list) *)
      contradiction.
Qed.