Require Import Coq.Lists.List.
Require Import Coq.Reals.Reals.
Require Import Coq.micromega.Lra.
Import ListNotations.
Open Scope R_scope.

(* Pre: no special constraints for `below_threshold` *)
Definition problem_52_pre (l : list R) : Prop := True.

Definition problem_52_spec (l : list R) (t : R) (output : bool) : Prop :=
  (forall x, In x l -> x < t) <-> (output = true).

Example test_problem_52 : problem_52_spec [1.5; 1000; 500; 250; 125; 6.635714530100879; 62.5; 31.25] 2000000 true.
Proof.
  unfold problem_52_spec.
  split.
  - (* Left to Right implication *)
    intros H.
    reflexivity.
  - (* Right to Left implication *)
    intros _ x HIn.
    (* Simplify the membership hypothesis for the concrete list *)
    simpl in HIn.
    (* Break down the disjunctions generated by In *)
    destruct HIn as [H | [H | [H | [H | [H | [H | [H | [H | H]]]]]]]].
    + (* Case 1.5 = x *)
      rewrite <- H.
      lra.
    + (* Case 1000 = x *)
      rewrite <- H.
      lra.
    + (* Case 500 = x *)
      rewrite <- H.
      lra.
    + (* Case 250 = x *)
      rewrite <- H.
      lra.
    + (* Case 125 = x *)
      rewrite <- H.
      lra.
    + (* Case 6.635714530100879 = x *)
      rewrite <- H.
      lra.
    + (* Case 62.5 = x *)
      rewrite <- H.
      lra.
    + (* Case 31.25 = x *)
      rewrite <- H.
      lra.
    + (* Case False (end of list) *)
      contradiction.
Qed.