Require Import List.
Require Import ZArith.
Import ListNotations.

Open Scope Z_scope.

Definition abs_diff (a b : Z) : Z :=
  Z.abs (a - b).

Fixpoint compare_spec (game : list Z) (guess : list Z) (result : list Z) : Prop :=
  match game, guess, result with
  | [], [], [] => True
  | g :: gs, gu :: gus, r :: rs => r = abs_diff g gu /\ compare_spec gs gus rs
  | _, _, _ => False
  end.

Example test_case : compare_spec 
  [1%Z; 2%Z; 3%Z; 4%Z; 5%Z; 1%Z] 
  [1%Z; 2%Z; 3%Z; 4%Z; 2%Z; -2%Z] 
  [0%Z; 0%Z; 0%Z; 0%Z; 3%Z; 3%Z].
Proof.
  (* Unfold the fixpoint and simplify the expression *)
  simpl.
  (* Split the conjunctions generated by the recursive definition *)
  repeat split.
  (* Solve each equality by computation *)
  all: reflexivity.
Qed.