Require Import Coq.Lists.List.
Require Import Coq.ZArith.ZArith.
Require Import Coq.Sorting.Sorted.
Require Import Coq.Sorting.Permutation.
Require Import Coq.Arith.Arith.
Require Import Coq.micromega.Lia.

Import ListNotations.
Open Scope Z_scope.

Fixpoint get_evens (l : list Z) : list Z :=
  match l with
  | [] => []
  | x :: [] => [x]
  | x :: _ :: tl => x :: get_evens tl
  end.

Definition sort_even_spec (l res : list Z) : Prop :=
  length l = length res /\
  (forall i : nat, (i < length l)%nat -> Nat.odd i = true -> nth i l 0 = nth i res 0) /\
  Permutation (get_evens l) (get_evens res) /\
  Sorted Z.le (get_evens res).

Example test_sort_even_case : sort_even_spec 
  [5; -13; 3; -5; 2; -3; -2; 3; -8; 0; 1; -10; -9; -10] 
  [-9; -13; -8; -5; -2; -3; 1; 3; 2; 0; 3; -10; 5; -10].
Proof.
  unfold sort_even_spec.
  split.
  - (* 1. Length check *)
    simpl. reflexivity.
  - split.
    + (* 2. Odd indices check *)
      intros i Hlen Hodd.
      (* Efficiently handle indices by destructing specific number of times *)
      do 14 (destruct i as [|i]; [ 
        simpl in Hodd; try discriminate; simpl; reflexivity 
      | ]).
      (* Remaining case: i >= 14, which contradicts length *)
      simpl in Hlen; lia.
    + split.
      * (* 3. Permutation check *)
        simpl.
        (* Use count_occ to prove permutation of concrete lists *)
        apply Permutation_count_occ with (eq_dec := Z.eq_dec).
        intros x.
        simpl.
        (* Destruct each equality check generated by count_occ *)
        repeat match goal with
        | [ |- context [Z.eq_dec ?a x] ] => 
          destruct (Z.eq_dec a x); [ subst; simpl; reflexivity | ]
        end.
        simpl; reflexivity.
      * (* 4. Sorted check *)
        simpl.
        repeat (apply Sorted_cons; [ apply HdRel_cons; lia | ]).
        apply Sorted_nil.
Qed.