Require Import List.
Require Import ZArith.
Import ListNotations.

Open Scope Z_scope.

Definition abs_diff (a b : Z) : Z :=
  Z.abs (a - b).

Fixpoint compare_spec (game : list Z) (guess : list Z) (result : list Z) : Prop :=
  match game, guess, result with
  | [], [], [] => True
  | g :: gs, gu :: gus, r :: rs => r = abs_diff g gu /\ compare_spec gs gus rs
  | _, _, _ => False
  end.

Example test_compare_spec :
  compare_spec [11; 20; 30; 40; 20; 50; 30] [11; 20; 30; 40; 20; 50; 30] [0; 0; 0; 0; 0; 0; 0].
Proof.
  (* Unfold the fixpoint definition and simplify the structure *)
  simpl.
  (* Split the conjunctions generated by the list elements *)
  repeat split.
  (* For each subgoal (equality check), unfold abs_diff and compute the integer arithmetic *)
  all: unfold abs_diff; vm_compute; reflexivity.
Qed.