Require Import Coq.Lists.List.
Require Import Coq.ZArith.ZArith.
Require Import Coq.Bool.Bool.
Require Import Coq.micromega.Lia.
Import ListNotations.
Open Scope Z_scope.

Definition max_element_spec (l : list Z) (max_elem : Z) : Prop :=
  In max_elem l /\ (forall x, In x l -> x <= max_elem).

Example test_max_element : max_element_spec [-1; -2; -3; -4; -5] (-1).
Proof.
  unfold max_element_spec.
  split.
  - (* Prove that -1 is in the list [-1; -2; -3; -4; -5] *)
    simpl.
    left. reflexivity.
  - (* Prove that for all x in [-1; -2; -3; -4; -5], x <= -1 *)
    intros x H.
    simpl in H.
    (* Break down the disjunctions generated by In *)
    destruct H as [H1 | [H2 | [H3 | [H4 | [H5 | H6]]]]].
    + (* Case x = -1 *)
      rewrite <- H1.
      lia.
    + (* Case x = -2 *)
      rewrite <- H2.
      lia.
    + (* Case x = -3 *)
      rewrite <- H3.
      lia.
    + (* Case x = -4 *)
      rewrite <- H4.
      lia.
    + (* Case x = -5 *)
      rewrite <- H5.
      lia.
    + (* Case False (end of list) *)
      contradiction.
Qed.