Require Import Coq.Lists.List.
Require Import Coq.Arith.PeanoNat.
Require Import Coq.Bool.Bool.
Require Import Coq.micromega.Lia.
Import ListNotations.

Definition max_element_spec (l : list nat) (max_elem : nat) : Prop :=
  In max_elem l /\ (forall x, In x l -> x <= max_elem).

Example test_max_element : max_element_spec [1; 2; 3] 3.
Proof.
  unfold max_element_spec.
  split.
  - (* Prove that 3 is in the list [1; 2; 3] *)
    simpl.
    right. right. left. reflexivity.
  - (* Prove that for all x in [1; 2; 3], x <= 3 *)
    intros x H.
    simpl in H.
    (* Break down the disjunctions generated by In *)
    destruct H as [H1 | [H2 | [H3 | H4]]].
    + (* Case x = 1 *)
      rewrite H1.
      lia.
    + (* Case x = 2 *)
      rewrite H2.
      lia.
    + (* Case x = 3 *)
      rewrite H3.
      lia.
    + (* Case False (end of list) *)
      contradiction.
Qed.